# Generated by Django 4.2.7 on 2023-11-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iapp', '0005_remove_products_modify_at_products_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsimages',
            name='image_data',
        ),
        migrations.AddField(
            model_name='productsimages',
            name='image',
            field=models.ImageField(default='none', upload_to='product_images/'),
        ),
    ]
