# Generated by Django 4.2.7 on 2023-11-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iapp', '0006_remove_productsimages_image_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimages',
            name='image',
            field=models.ImageField(default='none', upload_to='media/'),
        ),
    ]
