# Generated by Django 4.2.7 on 2023-11-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iapp', '0008_alter_productsimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimages',
            name='image',
            field=models.ImageField(default='none', upload_to='Iapp/image'),
        ),
    ]
