# Generated by Django 4.2.7 on 2023-12-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iapp', '0012_cart_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
    ]
