# Generated by Django 4.2.7 on 2023-12-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iapp', '0013_ordereditems_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedItems',
        ),
    ]
