# Generated by Django 4.2.7 on 2023-12-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iapp', '0014_delete_ordereditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
    ]
