# Generated by Django 4.2.7 on 2023-12-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iapp', '0017_alter_products_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_code',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
