# Generated by Django 4.2.7 on 2023-12-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iapp', '0018_products_product_code_alter_products_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_code',
            new_name='product_cod',
        ),
    ]
