# Generated by Django 4.2.7 on 2023-12-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iapp', '0019_rename_product_code_products_product_cod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_cod',
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.CharField(default='unknown', max_length=20, primary_key=True, serialize=False),
        ),
    ]
