# Generated by Django 4.2.7 on 2023-12-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iapp', '0020_remove_products_product_cod_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.CharField(blank=True, default='unknown', max_length=20, primary_key=True, serialize=False),
        ),
    ]
