# Generated by Django 4.2.7 on 2023-12-28 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iapp', '0022_alter_products_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_variation',
            fields=[
                ('id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('features', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products_variation',
            },
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productsimages',
            name='image',
            field=models.ImageField(upload_to='Iapp/image'),
        ),
        migrations.DeleteModel(
            name='OrdersPayment',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='products_variation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Iapp.products'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Iapp.products_variation'),
        ),
        migrations.AlterField(
            model_name='productsinventory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Iapp.products_variation'),
        ),
    ]
