# Generated by Django 4.2.7 on 2023-12-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iapp', '0023_products_variation_remove_reviews_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_variation',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductsInventory',
        ),
    ]
